<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Tests\Platforms;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\SpannerPostgreSQLPlatform;

class SpannerPostgreSQLPlatformTest extends PostgreSQLPlatformTest
{
    public function createPlatform(): AbstractPlatform
    {
        return new SpannerPostgreSQLPlatform();
    }

    public function getGenerateTableSql(): string
    {
        return 'CREATE TABLE test (id INT GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE) NOT NULL, test VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))';
    }

    /** @return string[] */
    public function getGenerateTableWithMultiColumnUniqueIndexSql(): array
    {
        return [
            'CREATE TABLE test (foo VARCHAR(255) DEFAULT NULL, bar VARCHAR(255) DEFAULT NULL, PRIMARY KEY ("foo"))',
            'CREATE UNIQUE INDEX UNIQ_D87F7E0C8C73652176FF8CAA ON test (foo, bar)',
        ];
    }

    /** @return string[] */
    public function getQuotedColumnInPrimaryKeySQL(): array
    {
        return ['CREATE TABLE "quoted" ("create" VARCHAR(255) NOT NULL, PRIMARY KEY ("create"))'];
    }

    /** @return string[] */
    public function getQuotedColumnInIndexSQL(): array
    {
        return [
            'CREATE TABLE "quoted" ("create" VARCHAR(255) NOT NULL, PRIMARY KEY ("""create"""))',
            'CREATE INDEX IDX_22660D028FD6E0FB ON "quoted" ("create")',
        ];
    }

    /** @return string[] */
    public function getQuotedNameInIndexSQL(): array
    {
        return [
            'CREATE TABLE test (column1 VARCHAR(255) NOT NULL, PRIMARY KEY ("column1"))',
            'CREATE INDEX "key" ON test (column1)',
        ];
    }

    /** @return string[] */
    public function getQuotedColumnInForeignKeySQL(): array
    {
        return [
            'CREATE TABLE "quoted" ("create" VARCHAR(255) NOT NULL, foo VARCHAR(255) NOT NULL, "bar" VARCHAR(255) NOT NULL, PRIMARY KEY ("""create"""))',
            'CREATE INDEX IDX_22660D028FD6E0FB8C7365216D704F76 ON "quoted" ("create", foo, "bar")',
            'ALTER TABLE "quoted" ADD CONSTRAINT FK_WITH_RESERVED_KEYWORD FOREIGN KEY ("create", foo, "bar") REFERENCES "foreign" ("create", bar, "foo-bar")',
            'ALTER TABLE "quoted" ADD CONSTRAINT FK_WITH_NON_RESERVED_KEYWORD FOREIGN KEY ("create", foo, "bar") REFERENCES foo ("create", bar, "foo-bar")',
            'ALTER TABLE "quoted" ADD CONSTRAINT FK_WITH_INTENDED_QUOTATION FOREIGN KEY ("create", foo, "bar") REFERENCES "foo-bar" ("create", bar, "foo-bar")',
        ];
    }

    public function testGenerateTableWithAutoincrement(): void
    {
        $table = new \Doctrine\DBAL\Schema\Table('test');
        $table->addColumn('id', 'integer', ['autoincrement' => true]);
        $table->setPrimaryKey(['id']);

        $this->assertEquals(
            ['CREATE TABLE test (id INT GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE) NOT NULL, PRIMARY KEY (id))'],
            $this->platform->getCreateTableSQL($table),
        );
    }

    public function testGenerateUnloggedTable(): void
    {
        $table = new \Doctrine\DBAL\Schema\Table('mytable');
        $table->addColumn('foo', 'string');
        $table->addOption('unlogged', true);

        $this->assertEquals(
            ['CREATE TABLE mytable (foo VARCHAR NOT NULL, PRIMARY KEY ("foo"))'],
            $this->platform->getCreateTableSQL($table),
        );
    }

    public function testGetCreateTableSQLWithUniqueConstraints(): void
    {
        $table = new \Doctrine\DBAL\Schema\Table('foo');
        $table->addColumn('id', 'string');
        $table->addUniqueConstraint(['id'], 'test_unique_constraint');

        $this->assertEquals(
            ['CREATE TABLE foo (id VARCHAR NOT NULL, PRIMARY KEY ("id"))'],
            $this->platform->getCreateTableSQL($table),
        );
    }

    public function testGetCreateTableSQLWithColumnCollation(): void
    {
        $table = new \Doctrine\DBAL\Schema\Table('foo');
        $table->addColumn('id', 'string');
        $table->addOption('comment', 'foo');

        $this->assertEquals(
            [
                'CREATE TABLE foo (id VARCHAR NOT NULL, PRIMARY KEY ("id"))',
                "COMMENT ON TABLE foo IS 'foo'",
            ],
            $this->platform->getCreateTableSQL($table),
        );
    }

    public function testGeneratesTypeDeclarationForIntegers(): void
    {
        $this->assertSame(
            'INT GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)',
            $this->platform->getIntegerTypeDeclarationSQL(['autoincrement' => true]),
        );
    }

    public function testReturnsSmallIntTypeDeclarationSQL(): void
    {
        $this->assertSame(
            'SMALLINT GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)',
            $this->platform->getSmallIntTypeDeclarationSQL(['autoincrement' => true]),
        );
    }

    public function testGenerateTableWithAutoincrementDoesNotSetDefault(string $typeName = '', string $definition = ''): void
    {
        $this->markTestSkipped('Spanner PG requires mandatory PRIMARY KEY.');
    }

    public function testCreateTableWithAutoincrementAndNotNullAddsConstraint(string $typeName = '', string $definition = ''): void
    {
        $this->markTestSkipped('Spanner PG requires mandatory PRIMARY KEY.');
    }
}
