<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Tests\Platforms;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\SpannerPlatform;
use Doctrine\DBAL\Schema\DefaultExpression\CurrentDate;
use Doctrine\DBAL\Schema\DefaultExpression\CurrentTimestamp;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Types\Types;
use PHPUnit\Framework\Attributes\DataProvider;

class SpannerPlatformTest extends AbstractPlatformTestCase
{
    public function createPlatform(): AbstractPlatform
    {
        return new SpannerPlatform();
    }

    public function getGenerateTableSql(): string
    {
        return 'CREATE TABLE test (id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE), test STRING(255)) PRIMARY KEY (id)';
    }

    /** @return string[] */
    public function getGenerateTableWithMultiColumnUniqueIndexSql(): array
    {
        return [
            'CREATE TABLE test (foo STRING(255) NOT NULL, bar STRING(255)) PRIMARY KEY (foo)',
            'CREATE UNIQUE INDEX UNIQ_D87F7E0C8C73652176FF8CAA ON test (foo, bar)',
        ];
    }

    public function testGenerateTableWithMultiColumnUniqueIndex(): void
    {
        $table = new Table('test');
        $table->addColumn('foo', 'string', ['length' => 255, 'notnull' => true]);
        $table->addColumn('bar', 'string', ['length' => 255, 'notnull' => false]);
        $table->setPrimaryKey(['foo']);
        $table->addUniqueIndex(['foo', 'bar']);

        $this->assertEquals($this->getGenerateTableWithMultiColumnUniqueIndexSql(), $this->platform->getCreateTableSQL($table));
    }

    public function testCreateWithNoColumns(): void
    {
        $this->markTestSkipped('Spanner requires columns and PK');
    }

    public function getGenerateIndexSql(): string
    {
        return 'CREATE INDEX my_idx ON mytable (user_name, last_login)';
    }

    public function getGenerateUniqueIndexSql(): string
    {
        return 'CREATE UNIQUE INDEX index_name ON test (test, test2)';
    }

    public function getGenerateForeignKeySql(): string
    {
        return 'ALTER TABLE test ADD FOREIGN KEY (fk_name_id) REFERENCES other_table (id)';
    }

    /** @return string[] */
    public function getQuotedColumnInPrimaryKeySQL(): array
    {
        return ['CREATE TABLE `quoted` (`create` STRING(255) NOT NULL) PRIMARY KEY (`create`)'];
    }

    /** @return string[] */
    public function getQuotedColumnInIndexSQL(): array
    {
        return [
            'CREATE TABLE `quoted` (`create` STRING(255) NOT NULL) PRIMARY KEY (`create`)',
            'CREATE INDEX IDX_22660D028FD6E0FB ON `quoted` (`create`)',
        ];
    }

    public function testQuotedColumnInIndexPropagation(): void
    {
        $table = new Table('"quoted"');
        $table->addColumn('create', 'string', ['length' => 255, 'notnull' => true]);
        $table->setPrimaryKey(['create']);
        $table->addIndex(['create']);

        $this->assertEquals($this->getQuotedColumnInIndexSQL(), $this->platform->getCreateTableSQL($table));
    }

    /** @return string[] */
    public function getQuotedNameInIndexSQL(): array
    {
        return [
            'CREATE TABLE test (column1 STRING(255) NOT NULL) PRIMARY KEY (column1)',
            'CREATE INDEX `key` ON test (column1)',
        ];
    }

    public function testQuotedNameInIndexSQL(): void
    {
        $table = new Table('test');
        $table->addColumn('column1', 'string', ['length' => 255, 'notnull' => true]);
        $table->setPrimaryKey(['column1']);
        $table->addIndex(['column1'], 'key');

        $this->assertEquals($this->getQuotedNameInIndexSQL(), $this->platform->getCreateTableSQL($table));
    }

    /** @return string[] */
    public function getQuotedColumnInForeignKeySQL(): array
    {
        return [
            'CREATE TABLE `quoted` (`create` STRING(255) NOT NULL, foo STRING(255) NOT NULL, bar STRING(255) NOT NULL) PRIMARY KEY (`create`)',
            'CREATE INDEX IDX_22660D028FD6E0FB8C73652176FF8CAA ON `quoted` (`create`, foo, bar)',
            'ALTER TABLE `quoted` ADD CONSTRAINT FK_WITH_RESERVED_KEYWORD FOREIGN KEY (`create`, foo, bar) REFERENCES `foreign` (`create`, bar, foo-bar)',
            'ALTER TABLE `quoted` ADD CONSTRAINT FK_WITH_NON_RESERVED_KEYWORD FOREIGN KEY (`create`, foo, bar) REFERENCES foo (`create`, bar, foo-bar)',
            'ALTER TABLE `quoted` ADD CONSTRAINT FK_WITH_INTENDED_QUOTATION FOREIGN KEY (`create`, foo, bar) REFERENCES foo-bar (`create`, bar, foo-bar)',
        ];
    }

    public function testQuotedColumnInForeignKeyPropagation(): void
    {
        $table = new Table('"quoted"');
        $table->addColumn('create', 'string', ['length' => 255, 'notnull' => true]);
        $table->addColumn('foo', 'string', ['length' => 255, 'notnull' => true]);
        $table->addColumn('bar', 'string', ['length' => 255, 'notnull' => true]);
        $table->setPrimaryKey(['create']);

        $table->addForeignKeyConstraint('foreign', ['create', 'foo', 'bar'], ['create', 'bar', 'foo-bar'], [], 'FK_WITH_RESERVED_KEYWORD');
        $table->addForeignKeyConstraint('foo', ['create', 'foo', 'bar'], ['create', 'bar', 'foo-bar'], [], 'FK_WITH_NON_RESERVED_KEYWORD');
        $table->addForeignKeyConstraint('foo-bar', ['create', 'foo', 'bar'], ['create', 'bar', 'foo-bar'], [], 'FK_WITH_INTENDED_QUOTATION');

        $this->assertEquals($this->getQuotedColumnInForeignKeySQL(), $this->platform->getCreateTableSQL($table));
    }

    public function getQuotesReservedKeywordInUniqueConstraintDeclarationSQL(): string
    {
        return 'CONSTRAINT `select` UNIQUE (foo)';
    }

    public function getQuotesReservedKeywordInTruncateTableSQL(): string
    {
        return 'DELETE FROM `select` WHERE true';
    }

    public function getQuotesReservedKeywordInIndexDeclarationSQL(): string
    {
        return 'INDEX `select` (foo)';
    }

    /** @return string[] */
    public function getAlterStringToFixedStringSQL(): array
    {
        return ['ALTER TABLE mytable ALTER COLUMN name STRING(2)'];
    }

    /** @return string[] */
    public function getGeneratesAlterTableRenameIndexUsedByForeignKeySQL(): array
    {
        return [
            'DROP INDEX idx_foo',
            'CREATE INDEX idx_foo_renamed ON mytable (foo)',
        ];
    }

    /** @return string[] */
    public function getCommentOnColumnSQL(): array
    {
        return ['', '', ''];
    }

    public function testGetCommentOnColumnSQLWithoutQuoteCharacter(): void
    {
         $this->markTestSkipped('Spanner does not support COMMENT ON COLUMN');
    }

    public function testGetCommentOnColumnSQLWithQuoteCharacter(): void
    {
         $this->markTestSkipped('Spanner does not support COMMENT ON COLUMN');
    }

    protected function supportsCommentOnStatement(): bool
    {
        return false;
    }

    protected function getExpectedFixedLengthStringTypeDeclarationSQLNoLength(): string
    {
        return 'STRING(MAX)';
    }

    protected function getExpectedFixedLengthStringTypeDeclarationSQLWithLength(): string
    {
        return 'STRING(16)';
    }

    protected function getExpectedVariableLengthStringTypeDeclarationSQLNoLength(): string
    {
        return 'STRING(MAX)';
    }

    protected function getExpectedVariableLengthStringTypeDeclarationSQLWithLength(): string
    {
        return 'STRING(16)';
    }

    public function getExpectedFixedLengthBinaryTypeDeclarationSQLNoLength(): string
    {
        return 'BYTES(MAX)';
    }

    public function getExpectedFixedLengthBinaryTypeDeclarationSQLWithLength(): string
    {
        return 'BYTES(16)';
    }

    public function getExpectedVariableLengthBinaryTypeDeclarationSQLNoLength(): string
    {
        return 'BYTES(MAX)';
    }

    public function getExpectedVariableLengthBinaryTypeDeclarationSQLWithLength(): string
    {
        return 'BYTES(16)';
    }

    public function testAlterTableRenameIndex(): void
    {
        $this->markTestSkipped('Spanner does not support RENAME INDEX');
    }

    public function testQuotesAlterTableRenameIndex(): void
    {
        $this->markTestSkipped('Spanner does not support RENAME INDEX');
    }

    public function testAlterTableRenameIndexInSchema(): void
    {
        $this->markTestSkipped('Spanner does not support RENAME INDEX');
    }

    public function testQuotesAlterTableRenameIndexInSchema(): void
    {
        $this->markTestSkipped('Spanner does not support RENAME INDEX');
    }

    public function testGetDefaultValueDeclarationSQL(): void
    {
        // Spanner requires parentheses around literal default values
        self::assertEquals(" DEFAULT ('non_timestamp')", $this->platform->getDefaultValueDeclarationSQL([
            'type' => Type::getType(Types::STRING),
            'default' => 'non_timestamp',
        ]));
    }

    public function testGetDefaultValueDeclarationSQLDateTime(): void
    {
        $types = [
            Types::DATETIME_MUTABLE,
            Types::DATETIMETZ_MUTABLE,
            Types::DATETIME_IMMUTABLE,
            Types::DATETIMETZ_IMMUTABLE,
        ];
        foreach ($types as $type) {
            self::assertSame(
                ' DEFAULT (CURRENT_TIMESTAMP())',
                $this->platform->getDefaultValueDeclarationSQL([
                    'type'    => Type::getType($type),
                    'default' => new CurrentTimestamp(),
                ]),
            );
        }
    }

    public function testGetDefaultValueDeclarationSQLForIntegerTypes(): void
    {
        foreach ([Types::BIGINT, Types::INTEGER, Types::SMALLINT] as $type) {
            self::assertEquals(
                ' DEFAULT (1)',
                $this->platform->getDefaultValueDeclarationSQL([
                    'type'    => Type::getType($type),
                    'default' => 1,
                ]),
            );
        }
    }

    public function testGetDefaultValueDeclarationSQLForDateType(): void
    {
        foreach ([Types::DATE_MUTABLE, Types::DATE_IMMUTABLE] as $type) {
            self::assertSame(
                ' DEFAULT (CURRENT_DATE)',
                $this->platform->getDefaultValueDeclarationSQL([
                    'type'    => Type::getType($type),
                    'default' => new CurrentDate(),
                ]),
            );
        }
    }

    /** @return iterable<array{array<string, mixed>, string}> */
    public static function getGeneratesSmallFloatDeclarationSQL(): iterable
    {
        yield [[], 'FLOAT64'];
        yield [['unsigned' => true], 'FLOAT64'];
        yield [['unsigned' => false], 'FLOAT64'];
        yield [['precision' => 5], 'FLOAT64'];
        yield [['scale' => 5], 'FLOAT64'];
        yield [['precision' => 8, 'scale' => 2], 'FLOAT64'];
    }

    /** @param array<mixed> $column */
    #[DataProvider('getGeneratesSmallFloatDeclarationSQL')]
    public function testGeneratesSmallFloatDeclarationSQL(array $column, string $expectedSql): void
    {
        $this->assertSame('FLOAT64', $this->platform->getSmallFloatDeclarationSQL($column));
    }

    /** @return iterable<array{array<string, mixed>, string}> */
    public static function getGeneratesDecimalTypeDeclarationSQL(): iterable
    {
        yield [['precision' => 10, 'scale' => 0], 'NUMERIC'];
        yield [['precision' => 8, 'scale' => 2], 'NUMERIC'];
    }

    /** @return iterable<array{array<string, mixed>, string}> */
    public static function getGeneratesFloatDeclarationSQL(): iterable
    {
        yield [[], 'FLOAT64'];
        yield [['unsigned' => true], 'FLOAT64'];
        yield [['unsigned' => false], 'FLOAT64'];
        yield [['precision' => 5], 'FLOAT64'];
        yield [['scale' => 5], 'FLOAT64'];
        yield [['precision' => 8, 'scale' => 2], 'FLOAT64'];
    }

    /** @param array<mixed> $column */
    #[DataProvider('getGeneratesDecimalTypeDeclarationSQL')]
    public function testGeneratesDecimalTypeDeclarationSQL(array $column, string $expectedSql): void
    {
        $this->assertSame('NUMERIC', $this->platform->getDecimalTypeDeclarationSQL($column));
    }

    /** @param array<mixed> $column */
    #[DataProvider('getGeneratesFloatDeclarationSQL')]
    public function testGeneratesFloatDeclarationSQL(array $column, string $expectedSql): void
    {
        $this->assertSame('FLOAT64', $this->platform->getFloatDeclarationSQL($column));
    }

    public function testReturnsGuidTypeDeclarationSQL(): void
    {
        $this->assertSame('STRING(36)', $this->platform->getGuidTypeDeclarationSQL([]));
    }

    /** @param array<mixed> $column */
    #[DataProvider('asciiStringSqlDeclarationDataProvider')]
    public function testAsciiSQLDeclaration(string $expectedSql, array $column): void
    {
        $this->assertSame('STRING(' . $column['length'] . ')', $this->platform->getStringTypeDeclarationSQL($column));
    }

    /** @param array<string> $values */
    #[DataProvider('getEnumDeclarationSQLProvider')]
    public function testGetEnumDeclarationSQL(array $values, string $expectedSQL): void
    {
        $this->assertStringStartsWith('STRING', $this->platform->getStringTypeDeclarationSQL(['length' => 10]));
    }

    /** @param array<string> $values */
    #[DataProvider('getEnumDeclarationWithLengthSQLProvider')]
    public function testGetEnumDeclarationWithLengthSQL(array $values, int $length, string $expectedSql): void
    {
        $this->assertSame('STRING(' . $length . ')', $this->platform->getStringTypeDeclarationSQL(['length' => $length]));
    }

    public function testReturnsJsonbTypeDeclarationSQL(): void
    {
        $this->markTestSkipped('Spanner does not support JSONB');
    }

    public function testAlterTableChangeQuotedColumn(): void
    {
        $this->markTestSkipped('ALTER TABLE support is minimal');
    }

    public function testGetCommentOnColumnSQL(): void
    {
        $this->markTestSkipped('Spanner does not support COMMENT ON COLUMN');
    }

    public function testReturnsJsonTypeDeclarationSQL(): void
    {
        $this->assertSame('JSON', $this->platform->getJsonTypeDeclarationSQL([]));
    }

    public function testGetVariableLengthBinaryTypeDeclarationSQLNoLength(): void
    {
        $this->assertSame('BYTES(MAX)', $this->platform->getBinaryTypeDeclarationSQL([]));
    }

    public function testGetFixedLengthBinaryTypeDeclarationSQLNoLength(): void
    {
        $this->assertSame('BYTES(MAX)', $this->platform->getBinaryTypeDeclarationSQL(['fixed' => true]));
    }

    public function testGetVariableLengthStringTypeDeclarationSQLNoLength(): void
    {
        $this->assertSame('STRING(MAX)', $this->platform->getStringTypeDeclarationSQL([]));
    }

    public function testGetDecimalTypeDeclarationSQLNoPrecision(): void
    {
        $this->assertSame('NUMERIC', $this->platform->getDecimalTypeDeclarationSQL(['scale' => 10]));
    }

    public function testGetDecimalTypeDeclarationSQLNoScale(): void
    {
        $this->assertSame('NUMERIC', $this->platform->getDecimalTypeDeclarationSQL(['precision' => 10]));
    }

    public function testQuotedColumnInPrimaryKeyPropagation(): void
    {
        $table = new Table('"quoted"');
        $table->addColumn('create', 'string', ['length' => 255, 'notnull' => true]);
        $table->setPrimaryKey(['create']);

        $this->assertEquals($this->getQuotedColumnInPrimaryKeySQL(), $this->platform->getCreateTableSQL($table));
    }

    public function testAlterStringToFixedString(): void
    {
        $this->markTestSkipped('Spanner does not support fixed string differently');
    }

    public function testGeneratesAlterTableRenameIndexUsedByForeignKeySQL(): void
    {
        $this->markTestSkipped('ALTER TABLE support is minimal');
    }

    public function testGetCreateSchemaSQL(): void
    {
        $this->assertEquals('CREATE SCHEMA test', $this->platform->getCreateSchemaSQL('test'));
    }

    public function testQuoteStringLiteral(): void
    {
        $this->assertEquals("'It\'s a quote'", $this->platform->quoteStringLiteral("It's a quote"));
    }

    public function testQuoteIdentifier(): void
    {
        self::assertEquals('`test`', $this->platform->quoteIdentifier('test'));
        self::assertEquals('`test`.`test`', $this->platform->quoteIdentifier('test.test'));
    }
}
