<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Platforms;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\Spanner\SpannerMetadataProvider;
use Doctrine\DBAL\Schema\AbstractSchemaManager;
use Doctrine\DBAL\Schema\Metadata\MetadataProvider;
use Doctrine\DBAL\Schema\SpannerSchemaManager;

use function implode;
use function reset;

/**
 * Provides the behavior, features and SQL dialect of the Google Cloud Spanner database platform (PostgreSQL dialect).
 */
class SpannerPostgreSQLPlatform extends PostgreSQLPlatform
{
    public function getName(): string
    {
        return 'spanner_postgresql';
    }

    public function createSchemaManager(Connection $connection): AbstractSchemaManager
    {
        return new SpannerSchemaManager($connection, $this);
    }

    public function createMetadataProvider(Connection $connection): MetadataProvider
    {
        return new SpannerMetadataProvider($connection, $this);
    }

    public function getDateTimeFormatString(): string
    {
        return 'Y-m-d H:i:s.u';
    }

    public function getDateTimeTzFormatString(): string
    {
        return 'Y-m-d H:i:s.u';
    }

    /** @param array<string, mixed> $column */
    protected function _getCommonIntegerTypeDeclarationSQL(array $column): string
    {
        if (! empty($column['autoincrement'])) {
            return ' GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)';
        }

        return '';
    }

    /**
     * {@inheritDoc}
     *
     * Cloud Spanner requires a PRIMARY KEY for every table. If none is specified,
     * the implementation auto-selects the first column as the primary key to ensure
     * compatibility with generic DBAL schema definitions.
     *
     * @return list<string>
     */
    protected function _getCreateTableSQL(string $name, array $columns, array $options = []): array
    {
        $columnListSql = $this->getColumnDeclarationListSQL($columns);

        if (! empty($options['primary'])) {
            $columnListSql .= ', PRIMARY KEY (' . implode(', ', $options['primary']) . ')';
        } else {
            $firstColumn = reset($columns);
            if ($firstColumn !== false) {
                $columnListSql .= ', PRIMARY KEY (' . $this->quoteIdentifier($firstColumn['name']) . ')';
            }
        }

        $sql = 'CREATE TABLE ' . $name . ' (' . $columnListSql . ')';

        $sqls = [$sql];

        if (isset($options['indexes'])) {
            foreach ($options['indexes'] as $index) {
                $sqls[] = $this->getCreateIndexSQL($index, $name);
            }
        }

        if (isset($options['foreignKeys'])) {
            foreach ($options['foreignKeys'] as $foreignKey) {
                $sqls[] = $this->getCreateForeignKeySQL($foreignKey, $name);
            }
        }

        return $sqls;
    }
}
